import type { Prisma, UsageResource } from "../../../generated/prisma";

export const USAGE_RESOURCES: UsageResource[] = [
  "AI_MINUTES",
  "REALTIME_VOICE_MINUTES",
  "INCOMING_CALLS",
  "OUTGOING_CALLS",
  "MESSAGES",
  "SMS_MESSAGES",
  "AI_INPUT_TOKENS",
  "AI_OUTPUT_TOKENS",
  "KNOWLEDGE_STORAGE_MB",
  "KNOWLEDGE_BASES",
  "AGENTS",
  "APPOINTMENTS",
  "PHONE_NUMBERS",
  "WIDGETS",
  "CALENDAR_CONNECTIONS",
  "TOOL_EXECUTIONS",
  "EXTERNAL_PHONE_NUMBERS",
  "PHONE_VERIFICATION_ATTEMPTS",
  "PHONE_FORWARDING_TESTS",
  "PHONE_FORWARDING_ACTIVATIONS",
  "PORT_REQUESTS",
  "COMPLETED_PORTS",
  "FAILED_PORTS",
  "CUSTOMER_PROFILES_CREATED",
  "CUSTOMER_PROFILES_UPDATED",
  "TIMELINE_WRITES",
  "TIMELINE_READS",
  "AI_SUMMARY_GENERATIONS",
  "AI_SUMMARY_INPUT_TOKENS",
  "AI_SUMMARY_OUTPUT_TOKENS",
  "AI_SUMMARY_COST_MICROS",
  "MEMORY_RETRIEVALS",
  "MEMORY_CONTEXT_TOKENS",
  "GREETING_GENERATIONS",
  "GREETING_CONTEXT_LOADS",
  "AUTOMATION_EXECUTIONS",
  "AUTOMATION_SMS_SENT",
  "AUTOMATION_EMAILS_SENT",
  "AUTOMATION_CALLS_SCHEDULED",
  "WORKFLOW_TEMPLATE_ACTIVATIONS",
  "OUTBOUND_CALLS",
  "OUTBOUND_MINUTES",
  "OUTBOUND_RECORDINGS",
  "OUTBOUND_TRANSCRIPTS",
  "QUALIFICATION_ATTEMPTS",
  "CAMPAIGN_TARGETS",
  "CAMPAIGN_CALLS",
  "CAMPAIGN_MINUTES",
  "LEAD_IMPORTS",
  "IMPORTED_LEADS",
  "CSV_UPLOADS",
];

export interface TrackUsageInput {
  organizationId: string;
  resourceType: UsageResource;
  quantity?: number;
  idempotencyKey?: string;
  metadata?: Prisma.InputJsonValue;
  occurredAt?: Date;
}

export interface UsagePeriod {
  start: Date;
  end: Date;
  source: "SUBSCRIPTION" | "TRIAL" | "CALENDAR";
}
