ALTER TYPE "UsageResource" ADD VALUE IF NOT EXISTS 'MEMORY_RETRIEVALS';
ALTER TYPE "UsageResource" ADD VALUE IF NOT EXISTS 'MEMORY_CONTEXT_TOKENS';

ALTER TABLE "analytics_daily_metrics"
  ADD COLUMN "recognizedCallers" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "memoryContextLoads" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "personalizedGreetings" INTEGER NOT NULL DEFAULT 0;
