ALTER TYPE "UsageResource" ADD VALUE IF NOT EXISTS 'GREETING_GENERATIONS';
ALTER TYPE "UsageResource" ADD VALUE IF NOT EXISTS 'GREETING_CONTEXT_LOADS';

ALTER TABLE "Organization"
  ADD COLUMN "personalizedGreetingsEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "greetingRecencyWindowDays" INTEGER NOT NULL DEFAULT 90,
  ADD COLUMN "greetingConfidenceThreshold" TEXT NOT NULL DEFAULT 'MEDIUM';

ALTER TABLE "analytics_daily_metrics"
  ADD COLUMN "greetingLevel0" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "greetingLevel1" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "greetingLevel2" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "greetingLevel3" INTEGER NOT NULL DEFAULT 0;
